"""Scoring engine weights and factor codes configuration."""

# Risk Scoring Weights (Section 14 of PhishGraph specification)
WEIGHT_TI_MALICIOUS_REPUTATION = 35
WEIGHT_TI_PHISHING_FEED_MATCH = 30
WEIGHT_BRAND_IMPERSONATION = 20
WEIGHT_DOMAIN_AGE_UNDER_7_DAYS = 18
WEIGHT_DOMAIN_AGE_UNDER_30_DAYS = 12
WEIGHT_PUNYCODE_HOMOGRAPH = 15
WEIGHT_IP_HOSTNAME = 10
WEIGHT_SUSPICIOUS_KEYWORDS_MULTIPLE = 10
WEIGHT_SUSPICIOUS_KEYWORDS_SINGLE = 5
WEIGHT_CROSS_DOMAIN_REDIRECT = 5
WEIGHT_MULTIPLE_REDIRECTS = 8
WEIGHT_INVALID_TLS = 8
WEIGHT_SELF_SIGNED_TLS = 5
WEIGHT_HIGH_URL_ENTROPY = 3
WEIGHT_DGA_ANOMALY = 18
WEIGHT_CORRELATED_INFRASTRUCTURE = 15

# Confidence Scoring Weights (Section 15 of PhishGraph specification)
CONF_BASE = 20
CONF_DNS_AVAILABLE = 15
CONF_RDAP_AVAILABLE = 20
CONF_TLS_AVAILABLE = 15
CONF_REDIRECT_TRACED = 10
CONF_TI_FEEDS_AGREEMENT = 20
